In [2]:
import pandas as pd
import os

In [3]:
pd.read_csv('daily8_5.csv')

,index,id,url,headline,dateline,text,tags,source,text_label,text_score,headline_label,headline_score
0,0,ETD_ARB_0000033,http://www.alittihad.ae/details.php?id=53&y=20...,الوثائق الرئاسية الأميركية··· متجاهلو التاريخ ...,2008-01-01,ربما نسي الكثيرون الآن الأمر التنفيذي الخاص با...,"['واشنطن', 'بوش']",Alittihad,False,False,negative,0.992800
1,1,ETD_ARB_0000035,http://www.alittihad.ae/details.php?id=55&y=20...,التنبؤات السنوية,2008-01-01,هذه هي حلقة التنبؤات المشتركة السنوية الرابعة ...,"['أوباما', 'كلينتون']",Alittihad,neutral,0.9615980386734009,neutral,0.974024
2,2,ETD_ARB_0000036,http://www.alittihad.ae/details.php?id=56&y=20...,شلهوب والحاسوب ·· يقدم وجبة تعليمية وفكرية ممت...,2008-01-01,''''كم هو جميل، هذا العالم السحري عالم الأطفال...,['بوش'],Alittihad,False,False,positive,0.836829
3,3,ETD_ARB_0000062,http://www.alittihad.ae/details.php?id=82&y=20...,48 قتيلاً وجريحاً باعتداءات متفرقة في العراق,2008-01-01,في استهداف جديد لعناصر ''''صحوة'''' العشائر ال...,['القاعدة'],Alittihad,neutral,0.8726907769838969,negative,0.701162
4,4,ETD_ARB_0000065,http://www.alittihad.ae/details.php?id=85&y=20...,النفط فوق 100 دولار·· هيلاري رئيسة لأميركا·· ا...,2008-01-01,استقبل العالم أول أيام العام الجديد ،2008 باحت...,['كلينتون'],Alittihad,neutral,0.9573821425437927,neutral,0.791736
...,...,...,...,...,...,...,...,...,...,...,...,...
331865,352,MTL_ARB_0409302,http://www.almustaqbal.com/v4/article.aspx?typ...,كونغ فو: كأس لبنان لفئة الصغار المرحلة الثانية,2005-03-18,نظم اتحاد الكونغ فو المرحلة الثانية من بطولة ل...,['بوش'],Almustaqbal,neutral,0.9892895817756653,neutral,0.994642
331866,353,MTL_ARB_0409311,http://www.almustaqbal.com/v4/article.aspx?typ...,"الـ""""سي آي ايه"""": سوريا وايران تقوّضان جهود أم...",2005-03-18,"اتهم مدير """"وكالة المخابرات المركزية الأميركية...",['القاعدة'],Almustaqbal,negative,0.6896247069040934,neutral,0.957517
331867,354,MTL_ARB_0409312,http://www.almustaqbal.com/v4/article.aspx?typ...,"""""النواب الأميركي"""" يقر """"تحرير لبنان وسوريا""""",2005-03-18,تبنى مجلس النواب الأميركي أمس بما يشبه الإجماع...,['بوش'],Almustaqbal,neutral,0.8265988826751709,neutral,0.982902
331868,355,MTL_ARB_0409313,http://www.almustaqbal.com/v4/article.aspx?typ...,"إجماع على اعتباره """"هجوم النزع الأخير"""" والحري...",2005-03-18,صفير في واشنطن يؤكد على الانسحاب قبل الانتخابا...,['واشنطن'],Almustaqbal,False,False,neutral,0.698540
331869,356,MTL_ARB_0409315,http://www.almustaqbal.com/v4/article.aspx?typ...,أنان يتوقع انسحاباً سورياً كاملاً قبل انتخابات...,2005-03-18,أعلن الأمين العام للأمم المتحدة كوفي أنان أمس ...,['واشنطن'],Almustaqbal,neutral,0.974044938882192,neutral,0.960120

In [36]:
df = pd.read_csv('daily8_5.csv')

In [5]:
df.text_label.value_counts()

neutral     172544
False        94164
negative     54450
positive     10712
Name: text_label, dtype: int64

In [6]:
df = df[df.text_label != 'False']
df.text_label.value_counts()

neutral     172544
negative     54450
positive     10712
Name: text_label, dtype: int64

In [7]:
df.to_csv('daily8_5_no_false.csv', index=False)

In [8]:
pd.to_datetime('09-11-2001')

Timestamp('2001-09-11 00:00:00')

In [18]:
import numpy as np

In [15]:
df.dateline= df.dateline.astype('datetime64')

In [31]:
(df.dateline.iloc[0] - spt_11th).dt.days

AttributeError: 'Timedelta' object has no attribute 'dt'

In [34]:
def within_30_days(df_dateline, date):
    
    if (df_dateline - spt_11th).days < 30 and (df_dateline - spt_11th).days > -30:
        return 1
    else:
        return 0

In [35]:
df['sept_11th'] = df.dateline.apply(within_30_days)
df

,index,id,url,headline,dateline,text,tags,source,text_label,text_score,headline_label,headline_score,sept_11th
1,1,ETD_ARB_0000035,http://www.alittihad.ae/details.php?id=55&y=20...,التنبؤات السنوية,2008-01-01,هذه هي حلقة التنبؤات المشتركة السنوية الرابعة ...,"['أوباما', 'كلينتون']",Alittihad,neutral,0.9615980386734009,neutral,0.974024,0
3,3,ETD_ARB_0000062,http://www.alittihad.ae/details.php?id=82&y=20...,48 قتيلاً وجريحاً باعتداءات متفرقة في العراق,2008-01-01,في استهداف جديد لعناصر ''''صحوة'''' العشائر ال...,['القاعدة'],Alittihad,neutral,0.8726907769838969,negative,0.701162,0
4,4,ETD_ARB_0000065,http://www.alittihad.ae/details.php?id=85&y=20...,النفط فوق 100 دولار·· هيلاري رئيسة لأميركا·· ا...,2008-01-01,استقبل العالم أول أيام العام الجديد ،2008 باحت...,['كلينتون'],Alittihad,neutral,0.9573821425437927,neutral,0.791736,0
5,5,ETD_ARB_0000066,http://www.alittihad.ae/details.php?id=86&y=20...,الصحوة تتحدى بن لادن: أفسدتم الأرض·· ونهايتكم ...,2008-01-01,أكد قياديون في ''''قوات الصحوة'''' اصرارهم على...,['القاعدة'],Alittihad,neutral,0.7232022285461426,negative,0.922155,0
6,6,ETD_ARB_0000067,http://www.alittihad.ae/details.php?id=87&y=20...,الأمن·· حلم العراقيين الوحيد في 2008,2008-01-01,مع بزوغ فجر أول يوم لسنة ،2008 يأمل العراقيون ...,['القاعدة'],Alittihad,positive,0.6070585250854492,positive,0.701550,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
331864,351,MTL_ARB_0409297,http://www.almustaqbal.com/v4/article.aspx?typ...,مساعدة مدرب الأنصار لألعاب القوى ميرنا اللاز ل...,2005-03-18,محمد دالاتي\nأكّدت ميرنا اللاز مساعدة مدرب ناد...,['القاعدة'],Almustaqbal,positive,0.8450518250465393,positive,0.702997,0
331865,352,MTL_ARB_0409302,http://www.almustaqbal.com/v4/article.aspx?typ...,كونغ فو: كأس لبنان لفئة الصغار المرحلة الثانية,2005-03-18,نظم اتحاد الكونغ فو المرحلة الثانية من بطولة ل...,['بوش'],Almustaqbal,neutral,0.9892895817756653,neutral,0.994642,0
331866,353,MTL_ARB_0409311,http://www.almustaqbal.com/v4/article.aspx?typ...,"الـ""""سي آي ايه"""": سوريا وايران تقوّضان جهود أم...",2005-03-18,"اتهم مدير """"وكالة المخابرات المركزية الأميركية...",['القاعدة'],Almustaqbal,negative,0.6896247069040934,neutral,0.957517,0
331867,354,MTL_ARB_0409312,http://www.almustaqbal.com/v4/article.aspx?typ...,"""""النواب الأميركي"""" يقر """"تحرير لبنان وسوريا""""",2005-03-18,تبنى مجلس النواب الأميركي أمس بما يشبه الإجماع...,['بوش'],Almustaqbal,neutral,0.8265988826751709,neutral,0.982902,0
331869,356,MTL_ARB_0409315,http://www.almustaqbal.com/v4/article.aspx?typ...,أنان يتوقع انسحاباً سورياً كاملاً قبل انتخابات...,2005-03-18,أعلن الأمين العام للأمم المتحدة كوفي أنان أمس ...,['واشنطن'],Almustaqbal,neutral,0.974044938882192,neutral,0.960120,0

In [42]:
df = pd.read_csv('daily8_5_no_false.csv')

In [43]:
df.dateline = df.dateline.astype('datetime64')

In [44]:
important_dates = {
    'september_11th': pd.to_datetime('09-11-2001'),
    'capture_of_baghdad': pd.to_datetime('04-09-2003'),
    'nick_berg': pd.to_datetime('05-12-2004'),
    'iran_nulcear': pd.to_datetime('08-30-2006'),
    'arab_spring': pd.to_datetime('12-20-2011')
}

for event, date in important_dates.items():
    df[event] = df.dateline.apply(within_30_days)
    
df

,index,id,url,headline,dateline,text,tags,source,text_label,text_score,headline_label,headline_score,september_11th,capture_of_baghdad,nick_berg,iran_nulcear,arab_spring
0,1,ETD_ARB_0000035,http://www.alittihad.ae/details.php?id=55&y=20...,التنبؤات السنوية,2008-01-01,هذه هي حلقة التنبؤات المشتركة السنوية الرابعة ...,"['أوباما', 'كلينتون']",Alittihad,neutral,0.961598,neutral,0.974024,0,0,0,0,0
1,3,ETD_ARB_0000062,http://www.alittihad.ae/details.php?id=82&y=20...,48 قتيلاً وجريحاً باعتداءات متفرقة في العراق,2008-01-01,في استهداف جديد لعناصر ''''صحوة'''' العشائر ال...,['القاعدة'],Alittihad,neutral,0.872691,negative,0.701162,0,0,0,0,0
2,4,ETD_ARB_0000065,http://www.alittihad.ae/details.php?id=85&y=20...,النفط فوق 100 دولار·· هيلاري رئيسة لأميركا·· ا...,2008-01-01,استقبل العالم أول أيام العام الجديد ،2008 باحت...,['كلينتون'],Alittihad,neutral,0.957382,neutral,0.791736,0,0,0,0,0
3,5,ETD_ARB_0000066,http://www.alittihad.ae/details.php?id=86&y=20...,الصحوة تتحدى بن لادن: أفسدتم الأرض·· ونهايتكم ...,2008-01-01,أكد قياديون في ''''قوات الصحوة'''' اصرارهم على...,['القاعدة'],Alittihad,neutral,0.723202,negative,0.922155,0,0,0,0,0
4,6,ETD_ARB_0000067,http://www.alittihad.ae/details.php?id=87&y=20...,الأمن·· حلم العراقيين الوحيد في 2008,2008-01-01,مع بزوغ فجر أول يوم لسنة ،2008 يأمل العراقيون ...,['القاعدة'],Alittihad,positive,0.607059,positive,0.701550,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237701,351,MTL_ARB_0409297,http://www.almustaqbal.com/v4/article.aspx?typ...,مساعدة مدرب الأنصار لألعاب القوى ميرنا اللاز ل...,2005-03-18,محمد دالاتي\nأكّدت ميرنا اللاز مساعدة مدرب ناد...,['القاعدة'],Almustaqbal,positive,0.845052,positive,0.702997,0,0,0,0,0
237702,352,MTL_ARB_0409302,http://www.almustaqbal.com/v4/article.aspx?typ...,كونغ فو: كأس لبنان لفئة الصغار المرحلة الثانية,2005-03-18,نظم اتحاد الكونغ فو المرحلة الثانية من بطولة ل...,['بوش'],Almustaqbal,neutral,0.989290,neutral,0.994642,0,0,0,0,0
237703,353,MTL_ARB_0409311,http://www.almustaqbal.com/v4/article.aspx?typ...,"الـ""""سي آي ايه"""": سوريا وايران تقوّضان جهود أم...",2005-03-18,"اتهم مدير """"وكالة المخابرات المركزية الأميركية...",['القاعدة'],Almustaqbal,negative,0.689625,neutral,0.957517,0,0,0,0,0
237704,354,MTL_ARB_0409312,http://www.almustaqbal.com/v4/article.aspx?typ...,"""""النواب الأميركي"""" يقر """"تحرير لبنان وسوريا""""",2005-03-18,تبنى مجلس النواب الأميركي أمس بما يشبه الإجماع...,['بوش'],Almustaqbal,neutral,0.826599,neutral,0.982902,0,0,0,0,0
237705,356,MTL_ARB_0409315,http://www.almustaqbal.com/v4/article.aspx?typ...,أنان يتوقع انسحاباً سورياً كاملاً قبل انتخابات...,2005-03-18,أعلن الأمين العام للأمم المتحدة كوفي أنان أمس ...,['واشنطن'],Almustaqbal,neutral,0.974045,neutral,0.960120,0,0,0,0,0

In [49]:
df[['september_11th', 'dateline']][df.september_11th == 1]

       september_11th   dateline
38981               1 2001-10-10
38982               1 2001-10-10
38983               1 2001-10-10
38984               1 2001-10-10
38985               1 2001-10-10
38986               1 2001-10-09
38987               1 2001-10-08
38988               1 2001-10-08
38989               1 2001-10-08
38990               1 2001-10-08
38991               1 2001-10-07
38992               1 2001-10-07
38993               1 2001-10-06
38994               1 2001-10-06
38995               1 2001-10-06
38996               1 2001-10-05
38997               1 2001-10-05
38998               1 2001-10-04
38999               1 2001-10-04
39000               1 2001-10-04
39001               1 2001-10-04
39002               1 2001-10-03
39003               1 2001-10-03
39004               1 2001-10-03
39005               1 2001-10-02
39006               1 2001-10-02
39007               1 2001-10-02
39008               1 2001-10-02
39009               1 2001-10-02
39010               1 2001-10-01
39011               1 2001-10-01
39012               1 2001-10-01
39013               1 2001-10-01
39014               1 2001-10-01
39015               1 2001-09-30
39016               1 2001-09-30
39017               1 2001-09-30

In [53]:
final = pd.read_csv('final_df.csv')
final.dateline = final.dateline.astype('datetime64')
final

,id,url,headline,dateline,text,tags,source,text_label,text_score,headline_label,headline_score
0,ETD_ARB_0000035,http://www.alittihad.ae/details.php?id=55&y=20...,التنبؤات السنوية,2008-01-01,هذه هي حلقة التنبؤات المشتركة السنوية الرابعة ...,"['أوباما', 'كلينتون']",Alittihad,neutral,0.961598,neutral,0.974024
1,ETD_ARB_0000062,http://www.alittihad.ae/details.php?id=82&y=20...,48 قتيلاً وجريحاً باعتداءات متفرقة في العراق,2008-01-01,في استهداف جديد لعناصر ''''صحوة'''' العشائر ال...,['القاعدة'],Alittihad,neutral,0.872691,negative,0.701162
2,ETD_ARB_0000065,http://www.alittihad.ae/details.php?id=85&y=20...,النفط فوق 100 دولار·· هيلاري رئيسة لأميركا·· ا...,2008-01-01,استقبل العالم أول أيام العام الجديد ،2008 باحت...,['كلينتون'],Alittihad,neutral,0.957382,neutral,0.791736
3,ETD_ARB_0000066,http://www.alittihad.ae/details.php?id=86&y=20...,الصحوة تتحدى بن لادن: أفسدتم الأرض·· ونهايتكم ...,2008-01-01,أكد قياديون في ''''قوات الصحوة'''' اصرارهم على...,['القاعدة'],Alittihad,neutral,0.723202,negative,0.922155
4,ETD_ARB_0000067,http://www.alittihad.ae/details.php?id=87&y=20...,الأمن·· حلم العراقيين الوحيد في 2008,2008-01-01,مع بزوغ فجر أول يوم لسنة ،2008 يأمل العراقيون ...,['القاعدة'],Alittihad,positive,0.607059,positive,0.701550
...,...,...,...,...,...,...,...,...,...,...,...
237701,MTL_ARB_0409297,http://www.almustaqbal.com/v4/article.aspx?typ...,مساعدة مدرب الأنصار لألعاب القوى ميرنا اللاز ل...,2005-03-18,محمد دالاتي\nأكّدت ميرنا اللاز مساعدة مدرب ناد...,['القاعدة'],Almustaqbal,positive,0.845052,positive,0.702997
237702,MTL_ARB_0409302,http://www.almustaqbal.com/v4/article.aspx?typ...,كونغ فو: كأس لبنان لفئة الصغار المرحلة الثانية,2005-03-18,نظم اتحاد الكونغ فو المرحلة الثانية من بطولة ل...,['بوش'],Almustaqbal,neutral,0.989290,neutral,0.994642
237703,MTL_ARB_0409311,http://www.almustaqbal.com/v4/article.aspx?typ...,"الـ""""سي آي ايه"""": سوريا وايران تقوّضان جهود أم...",2005-03-18,"اتهم مدير """"وكالة المخابرات المركزية الأميركية...",['القاعدة'],Almustaqbal,negative,0.689625,neutral,0.957517
237704,MTL_ARB_0409312,http://www.almustaqbal.com/v4/article.aspx?typ...,"""""النواب الأميركي"""" يقر """"تحرير لبنان وسوريا""""",2005-03-18,تبنى مجلس النواب الأميركي أمس بما يشبه الإجماع...,['بوش'],Almustaqbal,neutral,0.826599,neutral,0.982902
237705,MTL_ARB_0409315,http://www.almustaqbal.com/v4/article.aspx?typ...,أنان يتوقع انسحاباً سورياً كاملاً قبل انتخابات...,2005-03-18,أعلن الأمين العام للأمم المتحدة كوفي أنان أمس ...,['واشنطن'],Almustaqbal,neutral,0.974045,neutral,0.960120

In [54]:
df = final

important_dates = {
    'september_11th': pd.to_datetime('09-11-2001'),
    'capture_of_baghdad': pd.to_datetime('04-09-2003'),
    'nick_berg': pd.to_datetime('05-12-2004'),
    'iran_nulcear': pd.to_datetime('08-30-2006'),
    'arab_spring': pd.to_datetime('12-20-2011')
}

for event, date in important_dates.items():
    df[event] = df.dateline.apply(within_30_days)
    
df

,id,url,headline,dateline,text,tags,source,text_label,text_score,headline_label,headline_score,september_11th,capture_of_baghdad,nick_berg,iran_nulcear,arab_spring
0,ETD_ARB_0000035,http://www.alittihad.ae/details.php?id=55&y=20...,التنبؤات السنوية,2008-01-01,هذه هي حلقة التنبؤات المشتركة السنوية الرابعة ...,"['أوباما', 'كلينتون']",Alittihad,neutral,0.961598,neutral,0.974024,0,0,0,0,0
1,ETD_ARB_0000062,http://www.alittihad.ae/details.php?id=82&y=20...,48 قتيلاً وجريحاً باعتداءات متفرقة في العراق,2008-01-01,في استهداف جديد لعناصر ''''صحوة'''' العشائر ال...,['القاعدة'],Alittihad,neutral,0.872691,negative,0.701162,0,0,0,0,0
2,ETD_ARB_0000065,http://www.alittihad.ae/details.php?id=85&y=20...,النفط فوق 100 دولار·· هيلاري رئيسة لأميركا·· ا...,2008-01-01,استقبل العالم أول أيام العام الجديد ،2008 باحت...,['كلينتون'],Alittihad,neutral,0.957382,neutral,0.791736,0,0,0,0,0
3,ETD_ARB_0000066,http://www.alittihad.ae/details.php?id=86&y=20...,الصحوة تتحدى بن لادن: أفسدتم الأرض·· ونهايتكم ...,2008-01-01,أكد قياديون في ''''قوات الصحوة'''' اصرارهم على...,['القاعدة'],Alittihad,neutral,0.723202,negative,0.922155,0,0,0,0,0
4,ETD_ARB_0000067,http://www.alittihad.ae/details.php?id=87&y=20...,الأمن·· حلم العراقيين الوحيد في 2008,2008-01-01,مع بزوغ فجر أول يوم لسنة ،2008 يأمل العراقيون ...,['القاعدة'],Alittihad,positive,0.607059,positive,0.701550,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237701,MTL_ARB_0409297,http://www.almustaqbal.com/v4/article.aspx?typ...,مساعدة مدرب الأنصار لألعاب القوى ميرنا اللاز ل...,2005-03-18,محمد دالاتي\nأكّدت ميرنا اللاز مساعدة مدرب ناد...,['القاعدة'],Almustaqbal,positive,0.845052,positive,0.702997,0,0,0,0,0
237702,MTL_ARB_0409302,http://www.almustaqbal.com/v4/article.aspx?typ...,كونغ فو: كأس لبنان لفئة الصغار المرحلة الثانية,2005-03-18,نظم اتحاد الكونغ فو المرحلة الثانية من بطولة ل...,['بوش'],Almustaqbal,neutral,0.989290,neutral,0.994642,0,0,0,0,0
237703,MTL_ARB_0409311,http://www.almustaqbal.com/v4/article.aspx?typ...,"الـ""""سي آي ايه"""": سوريا وايران تقوّضان جهود أم...",2005-03-18,"اتهم مدير """"وكالة المخابرات المركزية الأميركية...",['القاعدة'],Almustaqbal,negative,0.689625,neutral,0.957517,0,0,0,0,0
237704,MTL_ARB_0409312,http://www.almustaqbal.com/v4/article.aspx?typ...,"""""النواب الأميركي"""" يقر """"تحرير لبنان وسوريا""""",2005-03-18,تبنى مجلس النواب الأميركي أمس بما يشبه الإجماع...,['بوش'],Almustaqbal,neutral,0.826599,neutral,0.982902,0,0,0,0,0
237705,MTL_ARB_0409315,http://www.almustaqbal.com/v4/article.aspx?typ...,أنان يتوقع انسحاباً سورياً كاملاً قبل انتخابات...,2005-03-18,أعلن الأمين العام للأمم المتحدة كوفي أنان أمس ...,['واشنطن'],Almustaqbal,neutral,0.974045,neutral,0.960120,0,0,0,0,0